### ISSUE TITLE
Typo on line 577

### ISSUE THREAD

**Issue by andrewcstewart** [jeffkaufman/icdiff#53] opened 2015-08-24 21:41 UTC
```
574    for x in [a, b]:
575        if os.path.isdir(x):
576            codec_print("error: %s is a directory; did you mean to "
577                        "pass --recursive?" % x, optoins)
```

optoins -> options

**Comment by lurch** [comment] 2015-10-30 11:58
Duplicate of #49 ?

**Comment by jcrben** [comment] 2016-02-10 06:37
Yeah, this should be closed.

**Comment by albfan** [comment] 2017-05-21 08:01
Close this

**Closed** 2017-05-21 21:00 UTC
