### ISSUE TITLE
What error with it? I can't install it!

### ISSUE THREAD

**Issue by imahobbit** [jeffkaufman/icdiff#90] opened 2016-11-22 05:13 UTC
ashk@ashk:~$ pip3 install icdiff
Collecting icdiff
  Downloading icdiff-1.8.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-k85vtoxg/icdiff/setup.py", line 4, in <module>
        from icdiff import __version__
      File "/tmp/pip-build-k85vtoxg/icdiff/icdiff.py", line 433
        except BadOptionError, err:
                             ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-k85vtoxg/icdiff/

**Comment by imahobbit** [comment] 2016-12-04 05:04
Hi Guys! Did you sure you had test you code?
Using CI like Travis CI can make testing autoly.
Travis CI :  https://travis-ci.org/

**Comment by jeffkaufman** [comment] 2016-12-05 12:41
It looks like whoever packaged icdiff for pip added something python2-specific?  "except BadOptionError, err" doesn't occur in https://github.com/jeffkaufman/icdiff/blob/master/icdiff

**Comment by jeffkaufman** [comment] 2016-12-05 12:42
@vnitinv

**Comment by vnitinv** [comment] 2016-12-05 12:45
@jeffkaufman Will check and update tomorrow.  I do remember something like this was fixed in github (after I released in pypi) and those fix need to go into pypi.

**Comment by jeffkaufman** [comment] 2016-12-05 12:48
To reproduce the error:

* download https://pypi.python.org/packages/7e/42/462f19ced2f6041ac96a26e2b31d5d713c27bbcad8cdf3f66c97b7a4f583/icdiff-1.8.5.tar.gz from https://pypi.python.org/pypi/icdiff
* run it with python3: `python3 icdiff-1.8.5/icdiff.py`

I think all it needs is changing `except BadOptionError, err` to `except BadOptionError as err`:

```
$ diff -u icdiff-pypi.py  icdiff-pypi-fixed.py 
--- icdiff-pypi.py	2016-12-05 12:43:46.628413390 +0000
+++ icdiff-pypi-fixed.py	2016-12-05 12:47:43.773193068 +0000
@@ -430,13 +430,13 @@
     def _process_long_opt(self, rargs, values):
         try:
             OptionParser._process_long_opt(self, rargs, values)
-        except BadOptionError, err:
+        except BadOptionError as err:
             self.largs.append(err.opt_str)
 
     def _process_short_opts(self, rargs, values):
         try:
             OptionParser._process_short_opts(self, rargs, values)
-        except BadOptionError, err:
+        except BadOptionError as err:
             self.largs.append(err.opt_str)
 
 def get_options():
```

**Comment by vnitinv** [comment] 2016-12-05 18:26
@imahobbit Check with latest code in PyPI

```pip install -U icdiff```

**Comment by imahobbit** [comment] 2017-01-22 10:52
## Look like a new problem 
~|⇒ sudo pip install git+https://github.com/jeffkaufman/icdiff.git

Collecting git+https://github.com/jeffkaufman/icdiff.git
  Cloning https://github.com/jeffkaufman/icdiff.git to /tmp/pip-ya02f3t0-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-ya02f3t0-build/setup.py", line 3, in <module>
        from icdiff import __version__
   ImportError: No module named 'icdiff'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-ya02f3t0-build/

**Comment by imahobbit** [comment] 2017-01-22 10:55
~|⇒ sudo pip install -U icdiff
Requirement already up-to-date: icdiff in /usr/local/lib/python2.7/dist-packages

**Comment by Encaitar** [comment] 2017-04-06 12:22
This (or a related issue) still seems to be a problem:

$ pip install git+https://github.com/jeffkaufman/icdiff.git

Collecting git+https://github.com/jeffkaufman/icdiff.git
  Cloning https://github.com/jeffkaufman/icdiff.git to /private/var/folders/81/t674skl95kv7vfpq81slstfh0000gn/T/pip-wp2aR6-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/81/t674skl95kv7vfpq81slstfh0000gn/T/pip-wp2aR6-build/setup.py", line 3, in <module>
        from icdiff import __version__
    ImportError: No module named icdiff
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/81/t674skl95kv7vfpq81slstfh0000gn/T/pip-wp2aR6-build/

**Comment by thaynan-almeida-movile** [comment] 2017-04-09 14:10
```Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 22, in <module>
    import requests, six
  File "/usr/lib/python2.7/dist-packages/requests/__init__.py", line 68, in <module>
    _attach_namespace(urllib3, 'requests.packages')
  File "/usr/lib/python2.7/dist-packages/requests/__init__.py", line 63, in _attach_namespace
    module = __import__(name)
  File "/usr/lib/python2.7/dist-packages/urllib3/contrib/pyopenssl.py", line 55, in <module>
    import OpenSSL.SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/SSL.py", line 112, in <module>
    if _lib.Cryptography_HAS_SSL_ST:
AttributeError: 'FFILibrary' object has no attribute 'Cryptography_HAS_SSL_ST'
```

Also,  I did get error above on pip install:
```bash
$ pip install https://github.com/jeffkaufman/icdiff.git
Collecting https://github.com/jeffkaufman/icdiff.git
  Downloading https://github.com/jeffkaufman/icdiff.git
     - 92kB 251kB/s
  Cannot unpack file /tmp/pip-VLy6OS-unpack/icdiff.git (downloaded from /tmp/pip-rqvpy9-build, content-type: text/html; charset=utf-8); cannot detect archive format
Cannot determine archive format of /tmp/pip-rqvpy9-build

/tmp/pip-rqvpy9-build$ ll
total 0
```

Code available at 
* https://raw.githubusercontent.com/jeffkaufman/icdiff/release-1.8.1/icdiff
* https://github.com/jeffkaufman/icdiff/blob/master/icdiff

It worked here: 
- http://www.jefftk.com/icdiff > "Install on Mac/Linux"
```bash
  curl -s https://raw.githubusercontent.com/jeffkaufman/icdiff/release-1.8.1/icdiff \
  | sudo tee /usr/local/bin/icdiff > /dev/null \
  && sudo chmod +rx /usr/local/bin/icdiff
```

*The install-with-curl command should also work on other unixes.*

*Or (mac only, depends on homebrew):*
`brew update && brew install icdiff`

**Comment by albfan** [comment] 2017-05-21 21:16
All this seems like several unrelated issues, better close and reopen as needed

**Comment by jeffkaufman** [comment] 2017-12-21 15:24
I've verified this is working now: `pip install icdiff` and `pip3 install icdiff` both work.

Feel free to file a new issue if you're still having trouble installing.

**Closed by jeffkaufman** 2017-12-21 15:24 UTC
