### ISSUE TITLE
Feature request: add support for piplining ("-" as argument)

### ISSUE THREAD

**Issue by X-Wei** [jeffkaufman/icdiff#78] opened 2016-05-06 17:10 UTC
I usually use `diff` in such a way (compare stdout with a given file): 

```
python "B.py" < B-small-attempt0.in | diff - B-small.out
```

however seems that icdiff donot support this kind of operation: 

```
$ python "B.py" < B-small-attempt0.in | icdiff - B-small.out
Traceback (most recent call last):
  File "/usr/local/bin/icdiff", line 9, in <module>
    load_entry_point('icdiff==1.7.5', 'console_scripts', 'icdiff')()
  File "/usr/local/lib/python2.7/dist-packages/icdiff.py", line 511, in start
    diff_files(options, a, b)
  File "/usr/local/lib/python2.7/dist-packages/icdiff.py", line 580, in diff_files
    lines_a = read_file(a, options)
  File "/usr/local/lib/python2.7/dist-packages/icdiff.py", line 550, in read_file
    with codecs.open(fname, encoding=options.encoding, mode="rb") as inf:
  File "/usr/lib/python2.7/codecs.py", line 878, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: '-'
```

Thus could you please add the support for `-` as argument ?

**Comment by joshkel** [comment] 2016-11-01 21:20
This is a duplicate of #64.

**Comment by jeffkaufman** [comment] 2017-12-21 15:36
Instead of writing:

     echo foo | icdiff - bar.txt

write:

     echo foo | icdiff <(cat) bar.txt

**Closed by jeffkaufman** 2017-12-21 15:36 UTC
